import { advancedScenarios, getOpponentFromPattern } from '../data/advancedScenarios';

// Fungsi untuk menghitung prediksi dasar (Round 1-7)
export const computeBasicPredictions = (rounds, userName, p8Name) => {
  const newRounds = [...rounds];

  // Round 1: automatic
  newRounds[0].userVs = p8Name;
  newRounds[0].p8Vs = userName || 'user';

  // Round 3: automatic, based on round 2 input
  if (newRounds[1].userVs !== '' || newRounds[1].p8Vs !== '') {
    newRounds[2].userVs = newRounds[1].p8Vs;
    newRounds[2].p8Vs = newRounds[1].userVs;
  }

  // Round 5: automatic, userVs from round 4 (p8Vs column)
  if (newRounds[3].p8Vs !== '') {
    newRounds[4].userVs = newRounds[3].p8Vs;
  }

  // Round 6: automatic, userVs from round 5 (p8Vs column)
  if (newRounds[4].p8Vs !== '') {
    newRounds[5].userVs = newRounds[4].p8Vs;
  }

  // Round 7: automatic
  if (newRounds[5].userVs !== '' && newRounds[5].p8Vs !== '') {
    newRounds[6].userVs = newRounds[5].p8Vs;
    newRounds[6].p8Vs = newRounds[5].userVs;
  }

  return newRounds;
};

// Fungsi untuk menghitung prediksi advanced (Round 8+)
export const computeAdvancedPredictions = (basicRounds, selectedScenario) => {
  if (!selectedScenario || !advancedScenarios[selectedScenario]) {
    return [];
  }

  const scenario = advancedScenarios[selectedScenario];
  const advancedRounds = [];

  scenario.rounds.forEach(roundData => {
    const opponent = roundData.pattern ? getOpponentFromPattern(roundData.pattern, basicRounds) : '';
    advancedRounds.push({
      round: roundData.round,
      userVs: opponent,
      p8Vs: '', // P8 column tetap kosong untuk advanced rounds
      isAdvanced: true,
      pattern: roundData.pattern
    });
  });

  return advancedRounds;
};

// Fungsi untuk mengecek apakah field auto-generated
export const isAutoGenerated = (round, field) => {
  if (round === 1) return true;
  if (round === 3) return true;
  if (round === 5 && field === 'userVs') return true;
  if (round === 6 && field === 'userVs') return true;
  if (round === 7) return true;
  if (round >= 8) return true; // Advanced rounds are auto-generated
  return false;
};

// Fungsi untuk mendapatkan placeholder yang dinamis
export const getPlaceholder = (roundIndex, field, rounds, userName, p8Name) => {
  const round = roundIndex + 1;
  
  if (field === 'p8Vs') {
    if (p8Name.trim()) {
      if (round === 5) {
        const round2P8Vs = rounds[1]?.p8Vs;
        return round2P8Vs ? `lawan dari ${round2P8Vs}` : `${p8Name} vs`;
      }
      return `${p8Name} vs`;
    }
    return 'p8 vs';
  }
  
  // Untuk userVs, gunakan nickname user jika sudah diisi
  if (field === 'userVs') {
    return userName.trim() ? `${userName} vs` : 'User vs';
  }
  
  return 'p8 vs';
};